# Generated by parley.nvim packaging/formula.lua; edit the source generator.
class Parley < Formula
  desc "Isolated Neovim chat application"
  homepage "https://github.com/xianxu/parley.nvim"
  url "https://github.com/xianxu/parley.nvim/archive/refs/tags/v2.3.0.tar.gz"
  sha256 "b8f2b2ada24adbe48dcf831896e8a7c28c76dc7d7e76648ccc34c45fb5e72631"
  license "MIT"

  depends_on "neovim"
  depends_on "ripgrep"

  def install
    libexec.install Dir["*", ".*"] - [".", "..", ".git"]
    (libexec/"packaging/parley").chmod 0755
    (share/"parley/config").install libexec/"packaging/starter-config/init.lua"
    (bin/"parley").write_env_script libexec/"packaging/parley",
      PARLEY_NVIM: Formula["neovim"].opt_bin/"nvim",
      PARLEY_RUNTIME: libexec,
      PARLEY_STARTER: share/"parley/config/init.lua"
  end

  test do
    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    assert_match "NVIM", shell_output("#{bin}/parley --version")
    assert_path_exists testpath/"config/parley/init.lua"
  end
end
