# Generated by parley.nvim packaging/formula.lua; edit the source generator.
class Parley < Formula
  desc "Isolated Neovim chat application"
  homepage "https://github.com/xianxu/parley.nvim"
  url "https://github.com/xianxu/parley.nvim/archive/refs/tags/v2.4.0.tar.gz"
  sha256 "03bf478df6fb8c4f3ef677a06b2d2ab29ce6381cbf0a26eda479ea331ca89e61"
  license "MIT"

  depends_on "neovim"
  depends_on "ripgrep"

  def install
    libexec.install Dir["*", ".*"] - [".", "..", ".git"]
    (libexec/"packaging/parley").chmod 0755
    (share/"parley/config").install libexec/"packaging/starter-config/init.lua"
    (bin/"parley").write_env_script libexec/"packaging/parley",
      PARLEY_NVIM: Formula["neovim"].opt_bin/"nvim",
      PARLEY_RUNTIME: libexec,
      PARLEY_STARTER: share/"parley/config/init.lua"
  end

  test do
    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    assert_match "NVIM", shell_output("#{bin}/parley --version")
    assert_path_exists testpath/"config/parley/init.lua"
  end
end
